name: CI - Department service
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Compile mvn
      run: mvn clean package -DskipTests
    - name: Build Docker image
      run: docker build -t department-service:v1 .
  deploy:
    env:
      APP_PORT: 8881
      DB_URL: jdbc:mysql://10.211.55.6:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      DB_USERNAME: "user1"
      DB_PASSWORD: "Password@2123"
    runs-on: [self-hosted]
    needs: build
    steps:
    - name: Stop and Remove Existing Containers
      run: docker compose down || true  # Ignore errors if no containers are running
    - name: Run with Docker Compose
      run: docker compose up -d
